In [1]:
import numpy

In [2]:
numpy.__version__

'1.21.5'

In [4]:
numpy.NaN

nan

In [6]:
numpy.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [9]:
import numpy as np

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a[2]

array([ 9, 10, 11, 12])

In [17]:
np.array([[0,0,0], [1,1,1]])

array([[0, 0, 0],
       [1, 1, 1]])

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [22]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [25]:
np.arange(-2,-100,-5)

array([ -2,  -7, -12, -17, -22, -27, -32, -37, -42, -47, -52, -57, -62,
       -67, -72, -77, -82, -87, -92, -97])

In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2])

In [29]:
x=[1,2]
x.append([10,11])

In [30]:
x

[1, 2, [10, 11]]

In [31]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr=np.array([[2,1,3,4,5,6,7,8,],[3,4,5,1,2,6,7,8]])
arr

array([[2, 1, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 1, 2, 6, 7, 8]])

In [37]:
np.sort(arr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [38]:
arr.ndim

2

In [39]:
arr.size

16

In [40]:
arr.shape

(2, 8)

In [43]:
arr=np.array([[[0,1,2,3],
           [4,5,6,7]], 
           
           [[0,1,2,3], 
          [4,5,6,7]],
          
          [[0,1,2,3],
          [4,5,6,7]]
          ])

arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [44]:
arr.ndim

3

In [45]:
arr.size

24

In [46]:
arr.shape

(3, 2, 4)

In [52]:
arr=np.array([[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5]])

In [51]:
arr.ndim

2

In [53]:
arr.size

5

In [54]:
arr.shape

(1, 5)

In [55]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [57]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
a.reshape(3,-1)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [59]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
a.reshape(3,-2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [63]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [65]:
a2=a[np.newaxis]
a2.shape

(1, 6)

In [66]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [67]:
row_vector=a[np.newaxis, :]
row_vector.shape

(1, 6)

In [68]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [69]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [70]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [71]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [72]:
b=np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [73]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [74]:
c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [75]:
c

array([[1, 2, 3, 4, 5, 6]])

# Indexing and slicing

In [76]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [77]:
data[0]

1

In [78]:
data[1]

2

In [79]:
data[2]

3

In [80]:
data[0:2]

array([1, 2])

In [81]:
data[1:]

array([2, 3])

In [82]:
data[-2:]

array([2, 3])

In [84]:
a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[condition]

In [87]:
condition=(a>=5)
a[condition]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
condition = (a%2==0)
a[condition]

array([ 2,  4,  6,  8, 10, 12])

In [89]:
condition = (a>2) & (a<11)
a[condition]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Creating array from existing data

In [101]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [95]:
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])

In [96]:
a_1

array([[1, 1],
       [2, 2]])

In [97]:
a_2

array([[3, 3],
       [4, 4]])

In [99]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [100]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [103]:
np.hstack((a_1, a_2)).shape

(2, 4)

In [105]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12] ,[13,14,15,16,17,18,19,20,21,22,23,24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [106]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [108]:
a= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
a.shape

(3, 4)

In [111]:
b=a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
c=a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [ ]:
array_1 - array_2
array_1 + array_2
array_1 * array_2
array_1 / array_2

In [115]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [116]:
a.sum()

10

In [121]:
b = np.array([[1,1], [2,3]])
b

array([[1, 1],
       [2, 3]])

In [122]:
b.sum(axis=0)

array([3, 4])

In [123]:
b.sum(axis=1)

array([2, 5])

In [124]:
data = np.array([1,2])
data

array([1, 2])

In [126]:
ones=np.ones(2)
ones

array([1., 1.])

In [127]:
data + ones

array([2., 3.])

In [128]:
data * ones

array([1., 2.])

In [129]:
data / ones

array([1., 2.])

In [130]:
data - ones

array([0., 1.])

# Broadcasting

In [131]:
data

array([1, 2])

In [132]:
data * 1.6

array([1.6, 3.2])

# More array operations

In [133]:
data.max()

2

In [134]:
data.min()

1

In [135]:
data.sum()

3

# Matrices

In [136]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [137]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [138]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [139]:
np.random.random((3,2))

array([[0.89220132, 0.3516162 ],
       [0.70979788, 0.67401135],
       [0.03779798, 0.32356795]])

In [142]:
data = np.array([[[1,2],[3,4]]])
data

array([[[1, 2],
        [3, 4]]])

In [143]:
data - ones

array([[[0., 1.],
        [2., 3.]]])

In [144]:
data / ones

array([[[1., 2.],
        [3., 4.]]])

In [145]:
data + ones

array([[[2., 3.],
        [4., 5.]]])

In [147]:
data * ones

array([[[1., 2.],
        [3., 4.]]])

# Dot product

In [148]:
a_1=np.array([[1,2,3], [4,5,6]])
a_1.shape

(2, 3)

In [150]:
a_2=np.array([[7,8], [9,10], [11,12]])
a_2.shape

(3, 2)

In [151]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [152]:
data=np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
data[0][1]

2

In [155]:
data[0,1]

2

In [156]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [158]:
data[0:2, 1]

array([2, 4])

# Matrix aggregation

In [159]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [160]:
data.max()

6

In [161]:
data.min()

1

In [162]:
data.sum()

21

In [163]:
data.std()

1.707825127659933

In [165]:
data.max(axis=1)

array([2, 4, 6])

# Transposing and reshaping

In [166]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [167]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [168]:
data_col=np.array([[1,2,3,4,5,6]])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [169]:
data_col.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [170]:
data_col = data_col.T
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [171]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [175]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [174]:
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# N-dimensional array

In [176]:
ndarr = np.array([[[1,2], [3,4]], 
                  [[5,6], [7,8]]
                 ])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [177]:
ndarr.shape

(2, 2, 2)

In [178]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [179]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [180]:
np.random.random((4,3,2))

array([[[0.60920365, 0.26479345],
        [0.04193837, 0.22126793],
        [0.47677318, 0.01830711]],

       [[0.90829313, 0.4001978 ],
        [0.96907213, 0.58128054],
        [0.1593168 , 0.92836722]],

       [[0.56267749, 0.91631654],
        [0.67586966, 0.21030425],
        [0.5164466 , 0.87517077]],

       [[0.70390317, 0.73231227],
        [0.50650715, 0.25500045],
        [0.9052305 , 0.56174797]]])

# Flatten N-dimensional array

In [181]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [182]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [183]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
error=(1/n)*np.sum(np.square(observed - prediction))